### NUMPY 

In [75]:
list1 =[2,3,4]
list2 =[3,5,6]
list1+list2

[2, 3, 4, 3, 5, 6]

In [38]:
import numpy as np
array1 = np.array([[2,3,4]])
array2 = np.array([7,9,10])
#1 2 3 + 2 3 4
#7 8 9 + 6 4 3
array_2d = np.array([[1,2,3],[7,8,9]])
#1 7 
#2 8 
#3 9  
print(array_2d.shape)
array1 +array2
array1+array_2d

(2, 3)


array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [39]:
print(array1 * array_2d)
print(np.multiply(array1,array_2d))
array_2d = array_2d.T
print(np.dot(array1,array_2d))
print(array1.shape)
print(array_2d.shape)

[[ 2  6 12]
 [14 24 36]]
[[ 2  6 12]
 [14 24 36]]
[[20 74]]
(1, 3)
(3, 2)


In [40]:
type(array1)

numpy.ndarray

In [42]:
array1 = np.array([[2,3,4]])
array2 = np.array([[7,9,10],[9,8,6]])
np.add(array1,array2)
array2[1:,1:]

array([[8, 6]])

### Numpy Matrix Formation

In [43]:
# 1 1 1 1
# 1 1 1 1
# 1 1 1 1
# 1 1 1 1
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
num = input()
np.full((2,2),num)

34


array([['34', '34'],
       ['34', '34']], dtype='<U2')

In [57]:
np.arange(1,50,6)


array([ 1,  7, 13, 19, 25, 31, 37, 43, 49])

In [59]:
np.sqrt(25)

5.0

In [77]:
import math as mp
power = mp.pow(5,6)
print(power)

15625.0


In [78]:
np.random.randint(1,15,size = (5,5))

array([[11, 10,  9,  8,  4],
       [ 7,  6,  2, 10,  4],
       [ 5,  9,  2, 12, 13],
       [11,  5,  1, 14,  4],
       [10,  3,  1,  5, 10]])

In [79]:
a = np.array([[1,2,3],[4,5,6]]) # 2*3
b = np.array([[6,7]])  # 1*2
a = a.reshape((6,1)) # Number of elements should be always kept same
print(np.dot(a,b))

[[ 6  7]
 [12 14]
 [18 21]
 [24 28]
 [30 35]
 [36 42]]


### Pandas


In [110]:
import pandas as pd
example = pd.DataFrame(["Alisha","Sampat","Arka","Aaushi","Kapil","Ananandhi"],index =[1,2,3,4,5,6],columns =["values"])
example

values
1     Alisha
2     Sampat
3       Arka
4     Aaushi
5      Kapil
6  Ananandhi

In [83]:
!wget https://www.dropbox.com/s/ogg0uy4jijp5ryt/housing.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [86]:
data = pd.read_csv('housing.csv')
print(data.describe())
print(data.info())

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.00000

In [88]:
print(data.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [93]:
list1 =data.columns.values
print(list1)
num = len(data.columns)
print("number of columns" , num)

['longitude' 'latitude' 'housing_median_age' 'total_rooms'
 'total_bedrooms' 'population' 'households' 'median_income'
 'median_house_value' 'ocean_proximity']
number of columns 10


In [94]:
new_data = data['population']
print(new_data.head())

0     322.0
1    2401.0
2     496.0
3     558.0
4     565.0
Name: population, dtype: float64


In [104]:
data.rename(columns = {'population' : 'pop'},inplace = True)
print(data.columns.values)

['longitude' 'latitude' 'housing_median_age' 'total_rooms'
 'total_bedrooms' 'pop' 'households' 'median_income' 'median_house_value'
 'ocean_proximity']


In [105]:
data.loc[0,'longitude'] = 0
print(data.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.00     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

      pop  households  median_income  median_house_value ocean_proximity  
0   322.0       126.0         8.3252            452600.0        NEAR BAY  
1  2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2   496.0       177.0         7.2574            352100.0        NEAR BAY  
3   558.0       219.0         5.6431            341300.0        NEAR BAY  
4   565.0       259.0         3.8462            342200.0        NEAR BAY  


In [106]:
data.rename(columns = {'pop' : 'population'},inplace = True)
print(data.columns.values)

['longitude' 'latitude' 'housing_median_age' 'total_rooms'
 'total_bedrooms' 'population' 'households' 'median_income'
 'median_house_value' 'ocean_proximity']


In [107]:
series = data['longitude']
print(series.head())

0      0.00
1   -122.22
2   -122.24
3   -122.25
4   -122.25
Name: longitude, dtype: float64


In [111]:
unique_values = data['ocean_proximity'].unique()
print(unique_values)

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [120]:
filtered_data = data['ocean_proximity'] == 'ISLAND'
results = data[filtered_data]
print(results.head())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0    215790000.0            450000.0   
8315      1100.0       431.0    283330000.0            414700.0   
8316       733.0       288.0    339060000.0            300000.0   
8317       341.0       160.0    273610000.0            450000.0   
8318       422.0       173.0    260420000.0            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318         

In [118]:
def convert(value):
    return value *10000
converted_data = data['median_income'].apply(convert)
print(converted_data.head())
data['median_income'] = converted_data
print(data.head())

0    832520000.0
1    830140000.0
2    725740000.0
3    564310000.0
4    384620000.0
Name: median_income, dtype: float64
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.00     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0    832520000.0            452600.0        NEAR BAY  
1      2401.0      1138.0    830140000.0            358500.0        NEAR BAY  
2       496.0       177.0    725740000.0            352100.0        NEAR BAY  
3       558.0       219.0    564310000.0            341300.0        NEAR BAY  
4       565.0       259.0    3846

In [124]:
def convert(value):
    return value /10000
converted_data = data['median_income'].apply(convert)
print(converted_data.head())
data['median_income'] = converted_data
print(data.head())

0    83252.0
1    83014.0
2    72574.0
3    56431.0
4    38462.0
Name: median_income, dtype: float64
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.00     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0        83252.0            452600.0        NEAR BAY  
1      2401.0      1138.0        83014.0            358500.0        NEAR BAY  
2       496.0       177.0        72574.0            352100.0        NEAR BAY  
3       558.0       219.0        56431.0            341300.0        NEAR BAY  
4       565.0       259.0        38462.0            3

In [127]:
#Data Categorisation
def convert_categories(value):
    if value>100000 :
        return 'high income'
    elif value >20000 and value<100000:
        return 'moderate-income'
    else:
        return 'low-incomes'
categories = data['median_income'].apply(convert_categories)
print(categories.head())

0    moderate-income
1    moderate-income
2    moderate-income
3    moderate-income
4    moderate-income
Name: median_income, dtype: object


In [129]:
#Data Aggregation inbuilt functions
summation = data['total_rooms'].sum()
minimum =data['total_rooms'].min()
print(summation)
print(minimum)

54402150.0
2.0


In [131]:
selected_data = ['population','ocean_proximity']
filtered_data = data[selected_data]
print(filtered_data.groupby('ocean_proximity').sum())

                 population
ocean_proximity            
<1H OCEAN        13889374.0
INLAND            9112744.0
ISLAND               3340.0
NEAR BAY          2817427.0
NEAR OCEAN        3598955.0
